apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-ecom-eks-cluster
  region: ap-northeast-2

vpc:
  id: 'vpc-02f306aae21577dd4'
  cidr: '10.0.0.0/24'
  subnets:
    private:
      dev-ecom-sub-pri01:
        id: 'subnet-06123259de8e70614'
        cidr: '10.0.0.128/26'
      dev-ecom-sub-pri02:
        id: 'subnet-0278c6b94902bd543'
        cidr: '10.0.0.192/26'

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: fp-mgmt
    selectors:
      - namespace: mgmt
        labels:
          type: mgmt
  - name: fp-backend
    selectors:
      - namespace: backend
        labels:
          type: backend

cloudWatch:
  clusterLogging: {}
